server:
  port: 80
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/mp?serverTimezone=UTC&characterEncoding=utf-8&useSSL=false
      username: root
      password: root

mybatis-plus:
  configuration:
    #打开sql日志输出
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
      logic-delete-field: deleted
    banner: false
  type-enums-package: com.example.enums
  type-aliases-package: com.example.domain
#jetcache替代springcache
jetcache:
  #每隔一分钟显示统计数据
  statIntervalMinutes: 1
  #本地方案
  local:
    default:
      type: linkedhashmap
      keyConvertor: fastjson
      valueEncode: java
      valueDecode: java
  #远程方案
  remote:
    default:
      type: redis
      host: localhost
      port: 6379
      keyConvertor: fastjson
      valueEncode: java
      valueDecode: java
      poolConfig:
        maxTotal: 50 #最大连接数





